/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreationWallet
 */
export interface CreationWallet {
  /**
   *
   * @type {string}
   * @memberof CreationWallet
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CreationWallet
   */
  description?: string;
}

/**
 * Check if a given object implements the CreationWallet interface.
 */
export function instanceOfCreationWallet(value: object): value is CreationWallet {
  return true;
}

export function CreationWalletFromJSON(json: any): CreationWallet {
  return CreationWalletFromJSONTyped(json, false);
}

export function CreationWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationWallet {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
  };
}

export function CreationWalletToJSON(json: any): CreationWallet {
  return CreationWalletToJSONTyped(json, false);
}

export function CreationWalletToJSONTyped(value?: CreationWallet | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
  };
}
