openapi: "3.0.3"
info:
  title: Api
  version: "1.0"
servers:
  - url: http://localhost:8080
security:
  - BearerAuth: []

tags:
  - name: auth
    description: For all authentications requests
paths:
  /auth/sign-up:
    post:
      tags:
        - auth
      security: []
      summary: Create new account with basic user role
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Credentials"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SignUpResult"
  /auth/sign-in:
    post:
      tags:
        - auth
      security: []
      summary: Login with and existing account
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Credentials"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SignInResult"
  /account/{accountId}/label:
    get:
      tags:
        - label
      parameters:
        - $ref: "#/components/parameters/AccountId"
      summary: Get all disponibles lables for the specified account
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Label"
    post:
      tags:
        - label
      parameters:
        - $ref: "#/components/parameters/AccountId"
      summary: Create new label for the specified account
      operationId: createOne
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreationLabel"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Label"
  /account/{accountId}/label/{labelId}:
    get:
      tags:
        - label
      parameters:
        - $ref: "#/components/parameters/AccountId"
        - $ref: "#/components/parameters/LabelId"
      summary: Get get one label by id for the specified account
      operationId: getOne
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Label"
    put:
      tags:
        - label
      parameters:
        - $ref: "#/components/parameters/AccountId"
        - $ref: "#/components/parameters/LabelId"
      summary: Update one label by id for the specified account
      operationId: updateOne
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Label"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Label"
  /account/{accountId}/wallet:
    get:
      tags:
        - wallet
      parameters:
        - $ref: "#/components/parameters/AccountId"
      summary: Get all disponibles wallet for the specified account
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Wallet"
    post:
      tags:
        - wallet
      parameters:
        - $ref: "#/components/parameters/AccountId"
      summary: Create new wallet for the specified account
      operationId: createOne
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreationWallet"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Wallet"
  /account/{accountId}/wallet/{walletId}:
    get:
      tags:
        - wallet
      parameters:
        - $ref: "#/components/parameters/AccountId"
        - $ref: "#/components/parameters/WalletId"
      summary: Get get one wallet by id for the specified account
      operationId: getOne
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Wallet"
    put:
      tags:
        - wallet
      parameters:
        - $ref: "#/components/parameters/AccountId"
        - $ref: "#/components/parameters/WalletId"
      summary: Update one wallet by id for the specified account
      operationId: updateOne
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UpdateWallet"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Wallet"

components:
  parameters:
    Id:
      name: id
      required: true
      in: path
      schema:
        type: string
        format: uuid
    AccountId:
      name: accountId
      required: true
      in: path
      schema:
        type: string
        format: uuid
    LabelId:
      name: labelId
      required: true
      in: path
      schema:
        type: string
        format: uuid
    WalletId:
      name: labelId
      required: true
      in: path
      schema:
        type: string
        format: uuid
    Page:
      name: page
      required: false
      in: query
      schema:
        type: number
        default: 1
    PageSize:
      name: pageSize
      required: false
      in: query
      schema:
        type: number
        default: 10
    Name:
      name: name
      required: false
      in: query
      schema:
        type: string
    Month:
      name: month
      required: false
      in: query
      schema:
        type: number
        minimum: 0
        maximum: 11
    Year:
      name: year
      required: false
      in: query
      schema:
        type: number

  schemas:
    CreationWallet:
      type: object
      properties:
        name:
          type: string
          example: Personal
        description:
          type: string
    UpdateWallet:
      type: object
      properties:
        id:
          type: string
          format: uuid
        isActive:
          type: boolean
      allOf:
        - $ref: "#/components/schemas/CreationWallet"
    Wallet:
      type: object
      allOf:
        - $ref: "#/components/schemas/UpdateWallet"
      properties:
        amount:
          type: number
          format: double
    CreationLabel:
      type: object
      properties:
        name:
          type: string
          example: FOOD
    Label:
      type: object
      allOf:
        - $ref: "#/components/schemas/CreationLabel"
      properties:
        id:
          type: string
          format: uuid

    Credentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    SignUpResult:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
    SignInResult:
      type: object
      properties:
        account:
          allOf:
            - $ref: "#/components/schemas/SignUpResult"
        token:
          type: string
    PaginationResult:
      type: object
      properties:
        totalPage:
          type: number
          minimum: 1
        page:
          type: number
          minimum: 1
        hasNext:
          type: boolean
        hasPrev:
          type: boolean
