/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationGoal, GetAllGoals200Response, Goal } from "../models/index";
import { CreationGoalFromJSON, CreationGoalToJSON, GetAllGoals200ResponseFromJSON, GetAllGoals200ResponseToJSON, GoalFromJSON, GoalToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface CreateOneGoalRequest {
  accountId: string;
  creationGoal?: CreationGoal;
}

export interface GetAllGoalsRequest {
  accountId: string;
  walletId?: string;
  name?: string;
  startingDate?: Date;
  endingDate?: Date;
}

export interface GetOneGoalRequest {
  accountId: string;
}

export interface UpdateOneGoalRequest {
  accountId: string;
  goal?: Goal;
}

/**
 *
 */
export class GoalApi extends runtime.BaseAPI {
  /**
   * create new goal for one account
   */
  async createOneGoalRaw(
    requestParameters: CreateOneGoalRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetAllGoals200Response>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/goal`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreationGoalToJSON(requestParameters["creationGoal"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GetAllGoals200ResponseFromJSON(jsonValue));
  }

  /**
   * create new goal for one account
   */
  async createOneGoal(requestParameters: CreateOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllGoals200Response> {
    const response = await this.createOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get all disponibles goal of one account
   */
  async getAllGoalsRaw(requestParameters: GetAllGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllGoals200Response>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllGoals().');
    }

    const queryParameters: any = {};

    if (requestParameters["walletId"] != null) {
      queryParameters["walletId"] = requestParameters["walletId"];
    }

    if (requestParameters["name"] != null) {
      queryParameters["name"] = requestParameters["name"];
    }

    if (requestParameters["startingDate"] != null) {
      queryParameters["startingDate"] = (requestParameters["startingDate"] as any).toISOString();
    }

    if (requestParameters["endingDate"] != null) {
      queryParameters["endingDate"] = (requestParameters["endingDate"] as any).toISOString();
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/goal`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GetAllGoals200ResponseFromJSON(jsonValue));
  }

  /**
   * Get all disponibles goal of one account
   */
  async getAllGoals(requestParameters: GetAllGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllGoals200Response> {
    const response = await this.getAllGoalsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get one goal of one account by it\'s id
   */
  async getOneGoalRaw(requestParameters: GetOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/goal/{goalId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * Get one goal of one account by it\'s id
   */
  async getOneGoal(requestParameters: GetOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.getOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * update one goal of one account
   */
  async updateOneGoalRaw(requestParameters: UpdateOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/goal/{goalId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: GoalToJSON(requestParameters["goal"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * update one goal of one account
   */
  async updateOneGoal(requestParameters: UpdateOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.updateOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
