/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationLabel, Label } from "../models/index";
import { CreationLabelFromJSON, CreationLabelToJSON, LabelFromJSON, LabelToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface CreateOneRequest {
  accountId: string;
  creationLabel?: CreationLabel;
}

export interface GetAllRequest {
  accountId: string;
}

export interface GetOneRequest {
  accountId: string;
  labelId: string;
}

export interface UpdateOneRequest {
  accountId: string;
  labelId: string;
  label?: Label;
}

/**
 *
 */
export class LabelApi extends runtime.BaseAPI {
  /**
   * Create new label for the specified account
   */
  async createOneRaw(requestParameters: CreateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOne().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/label`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreationLabelToJSON(requestParameters["creationLabel"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Create new label for the specified account
   */
  async createOne(requestParameters: CreateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.createOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get all disponibles lables for the specified account
   */
  async getAllRaw(requestParameters: GetAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Label>>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAll().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/label`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LabelFromJSON));
  }

  /**
   * Get all disponibles lables for the specified account
   */
  async getAll(requestParameters: GetAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Label>> {
    const response = await this.getAllRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get get one label by id for the specified account
   */
  async getOneRaw(requestParameters: GetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOne().');
    }

    if (requestParameters["labelId"] == null) {
      throw new runtime.RequiredError("labelId", 'Required parameter "labelId" was null or undefined when calling getOne().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/label/{labelId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"labelId"}}`, encodeURIComponent(String(requestParameters["labelId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Get get one label by id for the specified account
   */
  async getOne(requestParameters: GetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.getOneRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update one label by id for the specified account
   */
  async updateOneRaw(requestParameters: UpdateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOne().');
    }

    if (requestParameters["labelId"] == null) {
      throw new runtime.RequiredError("labelId", 'Required parameter "labelId" was null or undefined when calling updateOne().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/label/{labelId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"labelId"}}`, encodeURIComponent(String(requestParameters["labelId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: LabelToJSON(requestParameters["label"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Update one label by id for the specified account
   */
  async updateOne(requestParameters: UpdateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.updateOneRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
