/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationWallet, UpdateWallet, Wallet, WalletAutomaticIncome } from "../models/index";
import {
  CreationWalletFromJSON,
  CreationWalletToJSON,
  UpdateWalletFromJSON,
  UpdateWalletToJSON,
  WalletAutomaticIncomeFromJSON,
  WalletAutomaticIncomeToJSON,
  WalletFromJSON,
  WalletToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CreateOneWalletRequest {
  accountId: string;
  creationWallet?: CreationWallet;
}

export interface GetAllWalletsRequest {
  accountId: string;
}

export interface GetOneWalletRequest {
  accountId: string;
  walletId: string;
}

export interface UpdateOneWalletRequest {
  accountId: string;
  walletId: string;
  updateWallet?: UpdateWallet;
}

export interface UpdateOneWalletAutomaticIncomeRequest {
  accountId: string;
  walletId: string;
  walletAutomaticIncome?: WalletAutomaticIncome;
}

/**
 *
 */
export class WalletApi extends runtime.BaseAPI {
  /**
   * Create new wallet for the specified account
   */
  async createOneWalletRaw(requestParameters: CreateOneWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneWallet().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreationWalletToJSON(requestParameters["creationWallet"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
  }

  /**
   * Create new wallet for the specified account
   */
  async createOneWallet(requestParameters: CreateOneWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
    const response = await this.createOneWalletRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get all disponibles wallet for the specified account
   */
  async getAllWalletsRaw(requestParameters: GetAllWalletsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Wallet>>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllWallets().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/wallet`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WalletFromJSON));
  }

  /**
   * Get all disponibles wallet for the specified account
   */
  async getAllWallets(requestParameters: GetAllWalletsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Wallet>> {
    const response = await this.getAllWalletsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get get one wallet by id for the specified account
   */
  async getOneWalletRaw(requestParameters: GetOneWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneWallet().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling getOneWallet().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/wallet/{walletId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
  }

  /**
   * Get get one wallet by id for the specified account
   */
  async getOneWallet(requestParameters: GetOneWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
    const response = await this.getOneWalletRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update one wallet by id for the specified account
   */
  async updateOneWalletRaw(requestParameters: UpdateOneWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneWallet().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling updateOneWallet().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet/{walletId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateWalletToJSON(requestParameters["updateWallet"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
  }

  /**
   * Update one wallet by id for the specified account
   */
  async updateOneWallet(requestParameters: UpdateOneWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
    const response = await this.updateOneWalletRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update one wallet automatic income by walletId and accountId
   */
  async updateOneWalletAutomaticIncomeRaw(
    requestParameters: UpdateOneWalletAutomaticIncomeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Wallet>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneWalletAutomaticIncome().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling updateOneWalletAutomaticIncome().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet/{walletId}/automaticIncome`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: WalletAutomaticIncomeToJSON(requestParameters["walletAutomaticIncome"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
  }

  /**
   * Update one wallet automatic income by walletId and accountId
   */
  async updateOneWalletAutomaticIncome(requestParameters: UpdateOneWalletAutomaticIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
    const response = await this.updateOneWalletAutomaticIncomeRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
